'use strict'

/**
 * @memberof module:bfx-oss-docs
 * @enum {string}
 * @constant
 * @readonly
 */
const SECTION_TYPES = {
  /**
   * Single page
   */
  PAGE: 'page',

  /**
   * A group of pages with a menu in the sidebar for navigation
   */
  PAGE_GROUP: 'page-group',

  /**
   * A group of pages rendered into a single file, with a menu in the sidebar
   * for navigation
   */
  PAGE_GROUP_INLINE: 'page-group-inline',

  /**
   * API documentation, rendered from a JSON data object generated by the
   * language-specific documentation parser/generator.
   */
  API_DOCS: 'api-docs'
}

module.exports = SECTION_TYPES
