git submodule add https://github.com/bitfinexcom/bfx-hf-ui ./modules/bfx-hf-ui
git submodule add https://github.com/bitfinexcom/bfx-hf-ui-config ./modules/bfx-hf-ui-config
git submodule add https://github.com/bitfinexcom/bfx-hf-server ./modules/bfx-hf-server
git submodule add https://github.com/bitfinexcom/bfx-hf-models ./modules/bfx-hf-models
git submodule add https://github.com/bitfinexcom/bfx-hf-models-adapter-lowdb ./modules/bfx-hf-models-adapter-lowdb
git submodule add https://github.com/bitfinexcom/bfx-hf-models-adapter-sql ./modules/bfx-hf-models-adapter-sql
git submodule add https://github.com/bitfinexcom/bfx-hf-models-adapter-template ./modules/bfx-hf-models-adapter-template
git submodule add https://github.com/bitfinexcom/bfx-hf-ext-plugin-bitfinex ./modules/bfx-hf-ext-plugin-bitfinex
git submodule add https://github.com/bitfinexcom/bfx-hf-ext-plugin-dummy ./modules/bfx-hf-ext-plugin-dummy
git submodule add https://github.com/bitfinexcom/grenache-cli ./modules/grenache-cli
git submodule add https://github.com/bitfinexcom/grenache ./modules/grenache
git submodule add https://github.com/bitfinexcom/grenache-grape ./modules/grenache-grape
git submodule add https://github.com/bitfinexcom/grenache-rust ./modules/grenache-rust
git submodule add https://github.com/bitfinexcom/grenache-browser-http ./modules/grenache-browser-http
git submodule add https://github.com/bitfinexcom/grenache-nodejs-ws ./modules/grenache-nodejs-ws
git submodule add https://github.com/bitfinexcom/grenache-nodejs-ws-tls ./modules/grenache-nodejs-ws-tls
git submodule add https://github.com/bitfinexcom/grenache-nodejs-http ./modules/grenache-nodejs-http
git submodule add https://github.com/bitfinexcom/grenache-nodejs-base ./modules/grenache-nodejs-base
git submodule add https://github.com/bitfinexcom/grenache-nodejs-link ./modules/grenache-nodejs-link
git submodule add https://github.com/bitfinexcom/grenache-nodejs-utp ./modules/grenache-nodejs-utp
git submodule add https://github.com/bitfinexcom/grenache-nodejs-proxy ./modules/grenache-nodejs-proxy
git submodule add https://github.com/bitfinexcom/grenache-nodejs-zmq ./modules/grenache-nodejs-zmq
git submodule add https://github.com/bitfinexcom/grenache-ruby-base ./modules/grenache-ruby-base
git submodule add https://github.com/bitfinexcom/grenache-ruby-http ./modules/grenache-ruby-http
git submodule add https://github.com/bitfinexcom/grenache-ruby-ws ./modules/grenache-ruby-ws
git submodule add https://github.com/bitfinexcom/bfx-hf-chart ./modules/bfx-hf-chart
git submodule add https://github.com/bitfinexcom/bfx-api-node-models ./modules/bfx-api-node-models
git submodule add https://github.com/bitfinexcom/bfx-api-node-util ./modules/bfx-api-node-util
git submodule add https://github.com/bitfinexcom/bfx-hf-util ./modules/bfx-hf-util
git submodule add https://github.com/bitfinexcom/bfx-hf-indicators ./modules/bfx-hf-indicators
git submodule add https://github.com/bitfinexcom/bfx-hf-indicators-py ./modules/bfx-hf-indicators-py
git submodule add https://github.com/bitfinexcom/bfx-api-mock-srv ./modules/bfx-api-mock-srv
git submodule add https://github.com/bitfinexcom/bfx-api-node-mock-data ./modules/bfx-api-node-mock-data
git submodule add https://github.com/bitfinexcom/bfx-ws2-api-audit ./modules/bfx-ws2-api-audit
git submodule add https://github.com/bitfinexcom/lib-js-util-number ./modules/lib-js-util-number
git submodule add https://github.com/bitfinexcom/lib-js-util-math ./modules/lib-js-util-math
git submodule add https://github.com/bitfinexcom/lib-js-util-symbol ./modules/lib-js-util-symbol
git submodule add https://github.com/bitfinexcom/lib-js-util-currencies ./modules/lib-js-util-currencies
git submodule add https://github.com/bitfinexcom/wasteland ./modules/wasteland
git submodule add https://github.com/bitfinexcom/smidgen ./modules/smidgen
git submodule add https://github.com/bitfinexcom/caron ./modules/caron
git submodule add https://github.com/bitfinexcom/cbq-js ./modules/cbq-js
git submodule add https://github.com/bitfinexcom/pesto-rb ./modules/pesto-rb
git submodule add https://github.com/bitfinexcom/tpx ./modules/tpx
git submodule add https://github.com/bitfinexcom/affiliates-nicknames ./modules/affiliates-nicknames
git submodule add https://github.com/bitfinexcom/bitfinex-api-node ./modules/bitfinex-api-node
git submodule add https://github.com/bitfinexcom/bitfinex-api-py ./modules/bitfinex-api-py
git submodule add https://github.com/bitfinexcom/bitfinex-api-rb ./modules/bitfinex-api-rb
git submodule add https://github.com/bitfinexcom/bitfinex-api-go ./modules/bitfinex-api-go
git submodule add https://github.com/bitfinexcom/bfx-api-node-rest ./modules/bfx-api-node-rest
git submodule add https://github.com/bitfinexcom/bfx-api-node-ws1 ./modules/bfx-api-node-ws1
git submodule add https://github.com/bitfinexcom/bfx-hf-algo ./modules/bfx-hf-algo
git submodule add https://github.com/bitfinexcom/bfx-hf-algo-server ./modules/bfx-hf-algo-server
git submodule add https://github.com/bitfinexcom/moonbeam ./modules/moonbeam
git submodule add https://github.com/bitfinexcom/sunbeam ./modules/sunbeam
git submodule add https://github.com/bitfinexcom/eos-name-verify ./modules/eos-name-verify
git submodule add https://github.com/bitfinexcom/bfx-api-node-core ./modules/bfx-api-node-core
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-example ./modules/bfx-api-node-plugin-example
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-managed-candles ./modules/bfx-api-node-plugin-managed-candles
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-managed-ob ./modules/bfx-api-node-plugin-managed-ob
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-ob-checksum ./modules/bfx-api-node-plugin-ob-checksum
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-seq-audit ./modules/bfx-api-node-plugin-seq-audit
git submodule add https://github.com/bitfinexcom/bfx-api-node-plugin-wd ./modules/bfx-api-node-plugin-wd
git submodule add https://github.com/bitfinexcom/bfx-hf-strategy ./modules/bfx-hf-strategy
git submodule add https://github.com/bitfinexcom/bfx-hf-strategy-exec ./modules/bfx-hf-strategy-exec
git submodule add https://github.com/bitfinexcom/bfx-hf-strategy-py ./modules/bfx-hf-strategy-py
git submodule add https://github.com/bitfinexcom/bfx-hf-backtest ./modules/bfx-hf-backtest
git submodule add https://github.com/bitfinexcom/bfx-hf-data-server ./modules/bfx-hf-data-server
